# Copyright Abel Alexander John ;)
#

#The naming conventions used in Hyperledger Fabric 1.4 are not allowed in compose version 3 
version: '2'

services:
  #Couchdb for holding offchain data
  #
  offchaindb:
    container_name: offchaindb
    image: hyperledger/fabric-couchdb
    restart: always
    network_mode: "host"

    ports:
      - "5990:5985"